#!/bin/bash
#
# This script will save the current clipboard to optional filename.jpg or #.jpg.
#
# Usage: imclip [filename.png/jpg]

# Set filename
filename=
if [ -z ${1+x} ]; then
    for i in {1..99999999}; do
        filename="${i}.jpg"
        test -f "$filename" || break
    done
else
    filename="${1}"
fi

ext=$(echo "$filename" | grep -Po "(?<=\.)[^\.]*$")

case "$ext" in
        "jpg")
                t="image/jpeg"
                ;;
        "png")
                t="image/png"
                ;;
        *)
                echo "Error: Unknown extension \"$ext\"" && echo "Usage: imclip [filename.png/jpg]" && exit 1
                ;;
esac

test -z "${filename}" && { echo "Error: Empty Filename" && exit 1; }

xclip -selection clipboard -t $t -o > "$filename"
